const PRODUCTION =
  "mongodb+srv://KIUZMV:Bempercibal22@desparchate.1fks5.mongodb.net/proyect1?retryWrites=true&w=majority";
const DEVELOPMENT =
  "mongodb+srv://Bempercibal22:Bempercibal22@cluster0.70cwz.mongodb.net/proyect2?retryWrites=true&w=majority";

module.exports = {
  MONGODB: DEVELOPMENT,
  SECRET_KEY: "28435285",
  adminKey: "28435285",
  ciudades: [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Bucaramanga",
    "Santa Marta",
    "Manizales",
    "Pereira",
    "Cúcuta",
    "Ibagué",
    "Villavicencio",
    "Pasto",
    "Valledupar",
    "Armenia",
    "Montería",
    "Neiva",
    "Popoyán",
    "Tunja",
    "Quibdó",
    "Florencia",
    "Sincelejo",
    "Sincelejo",
    "Buenaventura",
    "Riohacha",
    "Soacha",
    "Yopal",
    "Barrancabermeja",
    "Tuluá",
    "Yumbo",
    "Palmira",
    "Zipaquirá",
    "Girardot",
    "Bello",
    "Floridablanca",
    "Duitama",
    "Soledad",
    "Rionegro",
    "Tumaco",
    "Facatativá",
    "Girón",
    "Jamundí",
    "Piedecuesta",
    "Mocoa",
    "Buga",
    "Ipiales",
    "Envigado",
    "Letecia",
    "Apartadó",
    "Arauca",
    "San José del Guavire",
    "Cartago",
  ],
};
